"""add last seen ids

Revision ID: a6f7b07f2c70
Revises: 482426f93439
Create Date: 2026-06-08 00:33:02.866305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f7b07f2c70'
down_revision: Union[str, Sequence[str], None] = '482426f93439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats_tg', sa.Column('last_seen_message_id', sa.BigInteger(), nullable=True))
    op.add_column('groups_vk', sa.Column('last_seen_post_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups_vk', 'last_seen_post_id')
    op.drop_column('chats_tg', 'last_seen_message_id')
    # ### end Alembic commands ###
